# Name of your application. Used to uniquely configure containers.
service: cites-checklist

# Credentials for your image host.
registry:
  server: ghcr.io
  username:
    - KAMAL_REGISTRY_USERNAME
  password:
    - KAMAL_REGISTRY_PASSWORD

# Use a different ssh user than root
ssh:
  user: wcmc

# Configure builder setup
builder:
  arch: amd64
  dockerfile: Dockerfile.deploy
  args:
    RUBY_VERSION: 2.6.10
